version: "2"

networks:
  default:
    external:
      name: cjp-demo-environment

services:
  
  proxy:
    container_name: cje.local
    #https://hub.docker.com/_/nginx/
    image: nginx:1.19.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - ./certs/cje.local.key:/etc/nginx/cje.local.key:ro
      - ./certs/cje.local.crt:/etc/nginx/cje.local.crt:ro
    depends_on: #to force proxy to start after:
      - cje

  cje:
    container_name: cje
    #https://hub.docker.com/r/cloudbees/jenkins-enterprise/
    image: cloudbees/jenkins-enterprise:2.150.3.2
    ports:
      - "50000:50000"
    environment:
      JENKINS_SLAVE_AGENT_PORT: "50000"
      JENKINS_HA: "false"
      JAVA_OPTS: "
        -Dhudson.TcpSlaveAgentListener.hostName=cje
        -Dhudson.TcpSlaveAgentListener.port=50000
        -Dhudson.udp=-1
        -Dhudson.DNSMultiCast.disabled=true
        -Djava.awt.headless=true
	-Djavax.net.ssl.trustStore=/var/jenkins_home/cacerts
	-Djavax.net.ssl.trustStorePassword=changeit
        -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York
        "
      JENKINS_OPTS: "--prefix=/cje"
    volumes:
      - ./data/cje:/var/jenkins_home
      - ./data/backups:/backups
      - ./certs/cacerts:/var/jenkins_home/cacerts:ro
